apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cdielk
  name: liberty-serverxml
  labels:
    app: liberty
data:
  server.xml: |-
     <?xml version="1.0" encoding="UTF-8"?>
     <server description="Default server">
         
          <!-- Enable features -->
          <featureManager>
             <feature>javaee-8.0</feature>
             <feature>microProfile-3.0</feature>
             <feature>appSecurity-2.0</feature>
             <feature>ldapRegistry-3.0</feature>
             <feature>jndi-1.0</feature>
          </featureManager>

         <!-- This template enables security. To get the full use of all the capabilities, a keystore and user registry are required. -->
    
         <!-- For the keystore, default keys are generated and stored in a keystore. To provide the keystore password, generate an 
         encoded password using bin/securityUtility encode and add it below in the password attribute of the keyStore element. 
         Then uncomment the keyStore element. -->
         <!--
         <keyStore password=""/> 
         -->
    
         <!--For a user registry configuration, configure your user registry. For example, configure a basic user registry using the
         basicRegistry element. Specify your own user name below in the name attribute of the user element. For the password, 
         generate an encoded password using bin/securityUtility encode and add it in the password attribute of the user element. 
         Then uncomment the user element. -->
         <basicRegistry id="basic" realm="BasicRealm"> 
         <!-- <user name="yourUserName" password="" />  --> 
         </basicRegistry>
    
         <!-- To allow access to this server from a remote client host="*" has been added to the following element -->
         <httpEndpoint id="defaultHttpEndpoint"
                  host="*"
                  httpPort="9080"
                  httpsPort="9443" />
                  
         <!-- Automatically expand WAR files and EAR files -->
         <applicationManager autoExpand="true"/>
         <ldapRegistry baseDN="o=ibm.com" host="10.90.109.175" id="Blue Pages" ldapType="IBM Tivoli Directory Server" port="389" realm="PATLdapRegistry" sslEnabled="false">

                <idsFilters groupFilter="(&amp;(cn=%v)(objectclass=groupOfUniqueNames))" groupMemberIdMap="groupOfUniqueNames:uniquemember" userFilter="(&amp;(emailAddress=%v)(objectclass=ibmPerson))" userIdMap="*:mail"/>
         </ldapRegistry>
         <dataSource jndiName="jdbc/defaultCICSDataSource">
                <jdbcDriver libraryRef="db2Lib"/>
                <properties.db2.jcc driverType="4"
                 serverName="10.112.220.226" 
                 portNumber="50000"
                 databaseName="GDWAGM"
                 user="gacdwadm"
                 password="RuscnyJPW9YH44xZ"/>
         </dataSource>

         <library id="db2Lib">
         <fileset dir="/usr/lpp/db2v11/jdbc/classes" includes="db2jcc4.jar 
           db2jcc_license_cisuz.jar" />
         </library>
         <application type="war" id="CDI-Analytics" name="CDI-Analytics" location="/opt/ibm/wlp/usr/servers/defaultServer/apps/CDI-Analytics.war" context-root="CDI-Analytics">
                <application-bnd>
                        <security-role name="CDISSO">
                                <special-subject type="ALL_AUTHENTICATED_USERS" />
                        </security-role>
                </application-bnd>
         </application>
      </server>